Insert into GEOGRAPHIC_AREA_HIERARCHY (GEOGRAPHIC_AREA_HIERARCHY) values ('2011GPH') ;

Insert into GEOGRAPHIC_AREA (GEOGRAPHIC_AREA_ID, NAME, EXT_CODE, GEOGRAPHIC_AREA_HIERARCHY, GEOGRAPHIC_AREA_TYPE, GEOGRAPHIC_LEVEL_TYPE, REL_GEOGRAPHIC_AREA_ID) values (1000001,'England and Wales','K04000001','2011GPH','EW','EW',null) ;
Insert into GEOGRAPHIC_AREA (GEOGRAPHIC_AREA_ID, NAME, EXT_CODE, GEOGRAPHIC_AREA_HIERARCHY, GEOGRAPHIC_AREA_TYPE, GEOGRAPHIC_LEVEL_TYPE, REL_GEOGRAPHIC_AREA_ID) values (1000002,'England','E92000001','2011GPH','COUNTRY','COUNTRY',1000001) ;
Insert into GEOGRAPHIC_AREA (GEOGRAPHIC_AREA_ID, NAME, EXT_CODE, GEOGRAPHIC_AREA_HIERARCHY, GEOGRAPHIC_AREA_TYPE, GEOGRAPHIC_LEVEL_TYPE, REL_GEOGRAPHIC_AREA_ID) values (1000003,'Wales','W92000004','2011GPH','COUNTRY','COUNTRY',1000001) ;
