---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: 1science/sbt

inputs:
  - name: dp-dd-database-loader

outputs:
  - name: target

run:
  path: dp-dd-database-loader/ci/scripts/build.sh
