Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('UK') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('GB') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('EW') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('COUNTRY') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('REGION') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('COUNTY') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('LA') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('MSOA') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('WPC') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('NUTS0') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('NUTS1') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('NUTS2') on conflict do nothing;
Insert into GEOGRAPHIC_LEVEL_TYPE (GEOGRAPHIC_LEVEL_TYPE) values ('NUTS3') on conflict do nothing;

Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('UK') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('GB') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('EW') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('COUNTRY') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('REGION') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('COUNTY') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('METROPOLITAN COUNTY') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('UNITARY AUTHORITY') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('LONDON BOROUGH') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('INNER AND OUTER LONDON') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('NON-METROPOLITAN DISTRICT') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('METROPOLITAN DISTRICT') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('METROPOLITAN BOROUGH') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('COUNCIL AREA') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('MSOA') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('WPC') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('NUTS0') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('NUTS1') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('NUTS2') on conflict do nothing;
Insert into GEOGRAPHIC_AREA_TYPE (GEOGRAPHIC_AREA_TYPE) values ('NUTS3') on conflict do nothing;
